defaults:
      - _self_
    
Env: Datasets.Suites.Classify.Classify
Dataset: torchvision.datasets.KMNIST
environment:
    dataset: ${dataset}
    low: 0
    high: 1
    batch_size: ${batch_size}
    num_workers: ${num_workers}
suite: classify
task_name: KMNIST
discrete: false
train_steps: 200000
stddev_schedule: 'linear(1.0,0.1,100000)'
frame_stack: null
action_repeat: null
nstep: 0
evaluate_per_steps: 1000
evaluate_episodes: 1
learn_per_steps: 1
learn_steps_after: 0
seed_steps: 50
explore_steps: 0
log_per_episodes: 300
RL: false
online: false  # Same as offline: true
