# Copyright (c) AGI.__init__. All Rights Reserved.
#
# This source code is licensed under the MIT license found in the
# MIT_LICENSE file in the root directory of this source tree.
name: ML
channels:
  - defaults
dependencies:
  - pip=21.1.3
  - python=3.8.13
  - numpy
  - pandas=1.3.0
  - seaborn=0.11.2
  - pip:
      - torch==1.11.0
      - torchvision==0.12.0
      - torchaudio==0.11.0
      - hydra-core==1.1.0
      - hydra-submitit-launcher==1.1.5
      - gym==0.25.0
      - ale-py==0.7.5
      - dm_control==1.0.3
      - PyOpenGL-accelerate==3.1.5
      - termcolor==1.1.0
      - wandb==0.12.17
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.4
      - opt_einsum_torch==0.1.0
      - einops==0.4.1
# Only for me
#   - cryptography
#   - pexpect
