# Copyright (c) AGI.__init__. All Rights Reserved.
#
# This source code is licensed under the MIT license found in the
# MIT_LICENSE file in the root directory of this source tree.
channels:
  - conda-forge
dependencies:
  - pip=22.3.1
  - python=3.10.8
  - hydra-core=1.1
  - pip:
      - torch==1.13.1
      - torchvision==0.14.1
      - torchaudio==0.13.1
      - pandas==1.5.3
      - gym==0.25.1
      - ale-py==0.7.5
      - dm_control==1.0.3
      - gym-super-mario-bros==7.4
      - PyOpenGL-accelerate==3.1.6
      - termcolor==1.1
      - seaborn==0.11.2
      - wandb==0.12.17
      - imageio==2.22
      - imageio-ffmpeg==0.4.7
      - einops==0.4.1
