defaults:
      - _self_
 
Env: Datasets.Suites.DMC.DMC
suite: dmc
task_name: humanoid_stand
discrete: false
action_repeat: 2
frame_stack: 3
nstep: 3
train_steps: 15000000
stddev_schedule: 'linear(1.0,0.1,2000000)'
lr: 8e-5
trunk_dim: 100

