defaults:
  - _self_

Env: Datasets.Suites.DMC.DMC
suite: dmc
task_name: walker_stand
discrete: false
action_repeat: 2
frame_stack: 3
nstep: 1
train_steps: 500000
stddev_schedule: 'linear(1.0,0.1,100000)'


batch_size: 512
