defaults:
  - _self_

Env: Datasets.Suites.SuperMario.SuperMario
suite: SuperMario
task_name: Mario
discrete: true
action_repeat: 4
truncate_episode_steps: 250
nstep: 3
frame_stack: 4
train_steps: 1000000
stddev_schedule: 'linear(1.0,0.1,800000)'

# Two augmentations
aug:
  _target_: Utils.Sequential
  _targets_: [RandomShiftsAug, IntensityAug]
  pad: 4
  noise: 0.05
